import { v4 as uuid } from "uuid";
 
export const products = [
  {
    id: uuid(),
    name: "Running Shoes",
    img: "https://picsum.photos/200/300?random=1",
    alt: "Running Shoes",
    brand: "Nike",
    newPrice: 1200,
    oldPrice: 1500,
    discount: 20,
    size: "M",
    ideaFor: "Men",
    rating: 4.2
  },
  {
    id: uuid(),
    name: "Sports T-shirt",
    img: "https://picsum.photos/200/300?random=2",
    alt: "Sports T-shirt",
    brand: "Adidas",
    newPrice: 800,
    oldPrice: 1000,
    discount: 20,
    size: "L",
    ideaFor: "Women",
    rating: 3.8
  },
  {
    id: uuid(),
    name: "Casual Jacket",
    img: "https://picsum.photos/200/300?random=3",
    alt: "Casual Jacket",
    brand: "Puma",
    newPrice: 2000,
    oldPrice: 2500,
    discount: 20,
    size: "XL",
    ideaFor: "Men",
    rating: 4.7
  },
  {
    id: uuid(),
    name: "Track Pants",
    img: "https://picsum.photos/200/300?random=4",
    alt: "Track Pants",
    brand: "Reebok",
    newPrice: 1500,
    oldPrice: 1800,
    discount: 17,
    size: "M",
    ideaFor: "Unisex",
    rating: 3.5
  },
  {
    id: uuid(),
    name: "Sneakers",
    img: "https://picsum.photos/200/300?random=5",
    alt: "Sneakers",
    brand: "Converse",
    newPrice: 2200,
    oldPrice: 2600,
    discount: 15,
    size: "L",
    ideaFor: "Men",
    rating: 4.9
  },
  {
    id: uuid(),
    name: "Yoga Pants",
    img: "https://picsum.photos/200/300?random=6",
    alt: "Yoga Pants",
    brand: "Nike",
    newPrice: 900,
    oldPrice: 1200,
    discount: 25,
    size: "S",
    ideaFor: "Women",
    rating: 4.1
  },
  {
    id: uuid(),
    name: "Winter Hoodie",
    img: "https://picsum.photos/200/300?random=7",
    alt: "Winter Hoodie",
    brand: "Adidas",
    newPrice: 1800,
    oldPrice: 2200,
    discount: 18,
    size: "XL",
    ideaFor: "Men",
    rating: 3.9
  },
  {
    id: uuid(),
    name: "Cap",
    img: "https://picsum.photos/200/300?random=8",
    alt: "Cap",
    brand: "Puma",
    newPrice: 400,
    oldPrice: 600,
    discount: 33,
    size: "Free",
    ideaFor: "Unisex",
    rating: 4.3
  },
  {
    id: uuid(),
    name: "Socks",
    img: "https://picsum.photos/200/300?random=9",
    alt: "Socks",
    brand: "Reebok",
    newPrice: 200,
    oldPrice: 300,
    discount: 33,
    size: "Free",
    ideaFor: "Unisex",
    rating: 2.8
  },
  {
    id: uuid(),
    name: "Backpack",
    img: "https://picsum.photos/200/300?random=10",
    alt: "Backpack",
    brand: "Nike",
    newPrice: 2500,
    oldPrice: 3000,
    discount: 17,
    size: "Free",
    ideaFor: "Unisex",
    rating: 4.6
  },
  {
    id: uuid(),
    name: "Sports Bra",
    img: "https://picsum.photos/200/300?random=11",
    alt: "Sports Bra",
    brand: "Adidas",
    newPrice: 1200,
    oldPrice: 1500,
    discount: 20,
    size: "M",
    ideaFor: "Women",
    rating: 3.7
  },
  {
    id: uuid(),
    name: "Running Shorts",
    img: "https://picsum.photos/200/300?random=12",
    alt: "Running Shorts",
    brand: "Puma",
    newPrice: 700,
    oldPrice: 1000,
    discount: 30,
    size: "L",
    ideaFor: "Men",
    rating: 4.0
  },
  {
    id: uuid(),
    name: "Formal Shoes",
    img: "https://picsum.photos/200/300?random=13",
    alt: "Formal Shoes",
    brand: "Bata",
    newPrice: 2500,
    oldPrice: 3200,
    discount: 22,
    size: "M",
    ideaFor: "Men",
    rating: 4.8
  },
  {
    id: uuid(),
    name: "Handbag",
    img: "https://picsum.photos/200/300?random=14",
    alt: "Handbag",
    brand: "Gucci",
    newPrice: 4500,
    oldPrice: 5000,
    discount: 10,
    size: "Free",
    ideaFor: "Women",
    rating: 4.4
  },
  {
    id: uuid(),
    name: "Smartwatch",
    img: "https://picsum.photos/200/300?random=15",
    alt: "Smartwatch",
    brand: "Apple",
    newPrice: 15000,
    oldPrice: 18000,
    discount: 17,
    size: "Free",
    ideaFor: "Unisex",
    rating: 4.9
  },
];

export default products;
